const fs = require('fs');
const path = require('path');

const KONTEN_DIR = path.join(__dirname, '../qu-life/konten');

const nabaData = {
    arabic: [
        "عَمَّ يَتَسَاۤءَلُوْنَۚ",
        "عَنِ النَّبَاِ الْعَظِيْمِۙ",
        "الَّذِيْ هُمْ فِيْهِ مُخْتَلِفُوْنَۗ",
        "كَلَّا سَيَعْلَمُوْنَۙ",
        "ثُمَّ كَلَّا سَيَعْلَمُوْنَ",
        "اَلَمْ نَجْعَلِ الْاَرْضَ مِهٰدًاۙ",
        "وَّالْجِبَالَ اَوْتَادًاۖ",
        "وَّخَلَقْنٰكُمْ اَزْوَاجًاۙ",
        "وَّجَعَلْنَا نَوْمَكُمْ سُبَاتًاۙ",
        "وَّجَعَلْنَا الَّيْلَ لِبَاسًاۙ",
        "وَّجَعَلْنَا النَّهَارَ مَعَاشًاۚ",
        "وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًاۙ",
        "وَّجَعَلْنَا سِرَاجًا وَّهَّاجًاۖ",
        "وَّاَنْزَلْنَا مِنَ الْمُعْصِرٰتِ مَاۤءً ثَجَّاجًاۙ",
        "لِّنُخْرِجَ بِهٖ حَبًّا وَّنَبَاتًاۙ",
        "وَّجَنّٰتٍ اَلْفَافًاۗ",
        "اِنَّ يَوْمَ الْفَصْلِ كَانَ مِيْقَاتًاۙ",
        "يَوْمَ يُنْفَخُ فِى الصُّوْرِ فَتَأْتُوْنَ اَفْوَاجًاۙ",
        "وَّفُتِحَتِ السَّمَاۤءُ فَكَانَتْ اَبْوَابًاۙ",
        "وَّسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَابًاۗ",
        "اِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًاۙ",
        "لِّلطّٰغِيْنَ مَاٰبًاۙ",
        "لّٰبِثِيْنَ فِيْهَآ اَحْقَابًاۚ",
        "لَا يَذُوْقُوْنَ فِيْهَا بَرْدًا وَّلَا شَرَابًاۙ",
        "اِلَّا حَمِيْمًا وَّغَسَّاقًاۙ",
        "جَزَاۤءً وِّفَاقًاۗ",
        "اِنَّهُمْ كَانُوْا لَا يَرْجُوْنَ حِسَابًاۙ",
        "وَّكَذَّبُوْا بِاٰيٰتِنَا كِذَّابًاۗ",
        "وَكُلَّ شَيْءٍ اَحْصَيْنٰهُ كِتٰبًاۙ",
        "فَذُوْقُوْا فَلَنْ نَّزِيْدَكُمْ اِلَّا عَذَابًاࣖ",
        "اِنَّ لِلْمُتَّقِيْنَ مَفَازًاۙ",
        "حَدَاۤىِٕقَ وَاَعْنَابًاۙ",
        "وَّكَوَاعِبَ اَتْرَابًاۙ",
        "وَّكَأْسًا دِهَاقًاۗ",
        "لَّا يَسْمَعُوْنَ فِيْهَا لَغْوًا وَّلَا كِذّٰبًا",
        "جَزَاۤءً مِّنْ رَّبِّكَ عَطَاۤءً حِسَابًاۙ",
        "رَّبِّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَا الرَّحْمٰنِ لَا يَمْلِكُوْنَ مِنْهُ خِطَابًاۚ",
        "يَوْمَ يَقُوْمُ الرُّوْحُ وَالْمَلٰۤىِٕكَةُ صَفًّاۙ لَّا يَتَكَلَّمُوْنَ اِلَّا مَنْ اَذِنَ لَهُ الرَّحْمٰنُ وَقَالَ صَوَابًا",
        "ذٰلِكَ الْيَوْمُ الْحَقُّۚ فَمَنْ شَاۤءَ اتَّخَذَ اِلٰى رَبِّهٖ مَاٰبًا",
        "اِنَّآ اَنْذَرْنٰكُمْ عَذَابًا قَرِيْبًا ەۙ يَّوْمَ يَنْظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُوْلُ الْكٰفِرُ يٰلَيْتَنِيْ كُنْتُ تُرٰبًاࣖ"
    ],
    translation: [
        "Tentang apakah mereka saling bertanya-tanya?",
        "Tentang berita yang besar (hari kebangkitan),",
        "yang dalam hal itu mereka berselisih.",
        "Sekali-kali tidak! Kelak mereka akan mengetahui,",
        "kemudian sekali-kali tidak! Kelak mereka akan mengetahui.",
        "Bukankah Kami telah menjadikan bumi sebagai hamparan,",
        "dan gunung-gunung sebagai pasak?",
        "Dan Kami menciptakan kamu berpasang-pasangan,",
        "dan Kami menjadikan tidurmu untuk istirahat,",
        "dan Kami menjadikan malam sebagai pakaian,",
        "dan Kami menjadikan siang untuk mencari penghidupan,",
        "dan Kami membangun di atasmu tujuh (langit) yang kokoh,",
        "dan Kami menjadikan pelita yang terang benderang (matahari),",
        "dan Kami turunkan dari awan, air yang banyak tercurah,",
        "agar Kami tumbuhkan dengan air itu biji-bijian dan tumbuh-tumbuhan,",
        "dan kebun-kebun yang lebat?",
        "Sungguh, hari keputusan adalah suatu waktu yang telah ditetapkan,",
        "(yaitu) pada hari (ketika) sangkakala ditiup, lalu kamu datang berbondong-bondong,",
        "dan langit pun dibukalah, maka terdapatlah beberapa pintu,",
        "dan gunung-gunung pun dijalankan, maka menjadilah ia fatamorgana.",
        "Sungguh, (neraka) Jahanam itu (padanya) ada tempat pengintai,",
        "bagi orang-orang yang melampaui batas (merupakan) tempat kembali.",
        "Mereka tinggal di sana dalam masa yang lama,",
        "mereka tidak merasakan kesejukan di dalamnya dan tidak (pula mendapat) minuman,",
        "selain air yang mendidih dan nanah,",
        "sebagai pembalasan yang setimpal.",
        "Sesungguhnya mereka dahulu tidak mengharapkan perhitungan,",
        "dan mereka benar-benar mendustakan ayat-ayat Kami.",
        "Dan segala sesuatu telah Kami catat dalam suatu Kitab (buku catatan amalan manusia).",
        "Maka rasakanlah! Tidak ada yang akan Kami tambahkan kepadamu selain azab.",
        "Sungguh, orang-orang yang bertakwa mendapat kemenangan,",
        "(yaitu) kebun-kebun dan buah anggur,",
        "dan gadis-gadis remaja yang sebaya,",
        "dan gelas-gelas yang penuh (berisi minuman).",
        "Di sana mereka tidak mendengar percakapan yang sia-sia maupun (perkataan) dusta.",
        "Sebagai balasan dari Tuhanmu dan pemberian yang cukup banyak,",
        "Tuhan (yang memelihara) langit dan bumi dan apa yang ada di antara keduanya; Yang Maha Pengasih, mereka tidak mampu berbicara dengan Dia.",
        "Pada hari, ketika Ruh dan para malaikat berdiri bersaf-saf, mereka tidak berkata-kata, kecuali siapa yang telah diberi izin kepadanya oleh Tuhan Yang Maha Pengasih dan dia berkata benar.",
        "Itulah hari yang pasti terjadi. Maka barangsiapa menghendaki, niscaya dia menempuh jalan kembali kepada Tuhannya.",
        "Sesungguhnya Kami telah memperingatkan kepadamu (orang kafir) azab yang dekat, pada hari manusia melihat apa yang telah diperbuat oleh kedua tangannya; dan orang kafir berkata, \"Alangkah baiknya seandainya dahulu aku jadi tanah.\""
    ],
    translation_en: [
        "About what are they asking one another?",
        "About the great news -",
        "That over which they are in disagreement.",
        "No! They are going to know.",
        "Then, no! They are going to know.",
        "Have We not made the earth a resting place?",
        "And the mountains as stakes?",
        "And We created you in pairs",
        "And made your sleep [a means for] rest",
        "And made the night as clothing",
        "And made the day for livelihood",
        "And constructed above you seven strong [heavens]",
        "And made [therein] a burning lamp",
        "And sent down, from the rain clouds, pouring water",
        "That We may bring forth thereby grain and vegetation",
        "And gardens of entwined growth.",
        "Indeed, the Day of Judgement is an appointed time -",
        "The Day the Horn is blown and you will come forth in multitudes",
        "And the heaven is opened and will become gateways",
        "And the mountains are removed and will be [but] a mirage.",
        "Indeed, Hell has been lying in wait",
        "For the transgressors, a place of return,",
        "In which they will remain for ages [unending].",
        "They will not taste therein [any] coolness or drink",
        "Except scalding water and [foul] purulence -",
        "An appropriate recompense.",
        "Indeed, they were not expecting an account",
        "And denied Our verses with [emphatic] denial.",
        "But all things We have enumerated in writing.",
        "\"So taste [the penalty], and never will We increase you except in torment.\"",
        "Indeed, for the righteous is attainment -",
        "Gardens and grapevines",
        "And full-breasted [companions] of equal age",
        "And a full cup.",
        "No ill speech will they hear therein or any falsehood -",
        "[As] reward from your Lord, a gift [according to] account,",
        "[From] the Lord of the heavens and the earth and whatever is between them, the Most Merciful. They possess not from Him [authority for] speech.",
        "The Day that the Spirit and the angels will stand in rows, they will not speak except for one whom the Most Merciful permits, and he will say what is correct.",
        "That is the True Day; so he who wills may take to his Lord a [way of] return.",
        "Indeed, We have warned you of a near punishment on the Day when a man will observe what his hands have put forth and the disbeliever will say, \"Oh, I wish that I were dust!\""
    ],
    translation_my: [
        "Tentang apakah orang-orang musyrik itu saling bertanya-tanya?",
        "Tentang berita yang besar, yaitu al-Qur’an yang agung ini yang mengabarkan tentang kebangkitan dan pembalasan.",
        "Yang mereka ragukan dan perselisihkan.",
        "Perkaranya tidak seperti yang mereka sangkakan. Kelak mereka akan mengetahui kebenaran al-Qur’an dan apa yang dikabarkannya.",
        "Kemudian sekali-kali tidak! Kelak mereka akan mengetahui kebenarannya dengan keyakinan yang pasti.",
        "Bukankah Kami telah menjadikan bumi terhampar bagi kalian seperti hamparan agar kalian bisa tinggal di atasnya?",
        "Dan (Kami jadikan) gunung-gunung sebagai pasak agar bumi tidak berguncang bersama kalian?",
        "Dan Kami menciptakan kalian berpasang-pasangan, laki-laki dan perempuan?",
        "Dan Kami menjadikan tidur kalian sebagai pemutus dari pekerjaan agar kalian bisa istirahat?",
        "Dan Kami menjadikan malam sebagai pakaian yang menutupi kalian dengan kegelapannya sebagaimana pakaian menutupi tubuh?",
        "Dan Kami menjadikan siang sebagai waktu untuk mencari penghidupan dan rezeki?",
        "Dan Kami membangun di atas kalian tujuh langit yang kokoh, kuat bangunannya, tidak ada keretakan dan tidak ada lubang padanya?",
        "Dan Kami menjadikan matahari sebagai pelita yang bersinar terang dan menyala-nyala?",
        "Dan Kami menurunkan dari awan yang memeras air, air hujan yang banyak tercurah?",
        "Agar Kami keluarkan dengan air itu biji-bijian yang dimakan manusia dan tumbuh-tumbuhan yang dimakan hewan ternak?",
        "Dan kebun-kebun yang lebat pepohonannya?",
        "Sesungguhnya Hari Keputusan antara makhluk adalah waktu yang telah ditetapkan bagi umat-umat terdahulu dan yang datang kemudian.",
        "Yaitu hari ketika Malaikat Israfil meniup sangkakala, lalu kalian datang berbondong-bondong.",
        "Dan langit dibuka, maka jadilah ia mempunyai pintu-pintu yang banyak untuk turunnya para malaikat.",
        "Dan gunung-gunung dijalankan dari tempat-tempatnya, maka jadilah ia seperti fatamorgana yang tidak memiliki hakikat.",
        "Sesungguhnya Neraka Jahanam adalah tempat yang menanti dan mengintai.",
        "Bagi orang-orang yang melampaui batas dalam kekafiran dan kemaksiatan sebagai tempat kembali.",
        "Mereka tinggal di dalamnya dalam masa yang sangat panjang, tidak ada ujungnya.",
        "Mereka tidak merasakan kesejukan di dalamnya yang mendinginkan panasnya neraka, dan tidak pula mendapatkan minuman yang menghilangkan dahaga.",
        "Kecuali air yang sangat panas dan nanah penghuni neraka.",
        "Sebagai balasan yang setimpal dengan amal perbuatan mereka yang buruk.",
        "Sesungguhnya mereka dahulu di dunia tidak takut akan adanya hisab (perhitungan amal), sehingga mereka tidak beramal untuk menghadapinya.",
        "Dan mereka mendustakan ayat-ayat Kami dengan pendustaan yang nyata.",
        "Dan segala sesuatu dari amal perbuatan mereka telah Kami catat dan Kami hitung dalam kitab catatan amal.",
        "Maka rasakanlah wahai orang-orang kafir azab ini, Kami tidak akan menambah kepada kalian kecuali azab di atas azab.",
        "Sesungguhnya bagi orang-orang yang bertakwa kepada Tuhannya dengan mengerjakan perintah-Nya dan menjauhi larangan-Nya, ada tempat kemenangan, yaitu Surga.",
        "Yaitu kebun-kebun dan buah anggur.",
        "Dan gadis-gadis remaja yang sebaya umurnya.",
        "Dan gelas-gelas yang penuh berisi khamar yang tidak memabukkan.",
        "Di dalam Surga itu mereka tidak mendengar perkataan yang tidak berguna dan tidak pula perkataan dusta.",
        "Sebagai balasan dan pemberian yang cukup banyak dari Tuhanmu.",
        "Tuhan yang memelihara langit dan bumi dan apa yang ada di antara keduanya, Yang Maha Pengasih. Mereka tidak memiliki kemampuan untuk berbicara di hadapan-Nya kecuali dengan izin-Nya.",
        "Pada hari ketika Jibril dan para malaikat berdiri bersaf-saf. Mereka tidak berkata-kata karena takut kepada Allah, kecuali siapa yang telah diberi izin oleh Tuhan Yang Maha Pengasih dan dia mengucapkan perkataan yang benar.",
        "Itulah Hari yang pasti terjadi, tidak ada keraguan padanya. Maka barangsiapa yang ingin selamat dari azabnya, hendaklah ia menempuh jalan kembali kepada Tuhannya dengan beriman dan beramal saleh.",
        "Sesungguhnya Kami telah memperingatkan kalian wahai manusia akan azab yang dekat, yaitu pada hari Kiamat, hari ketika manusia melihat apa yang telah diperbuat oleh kedua tangannya dari kebaikan dan keburukan. Dan orang kafir berkata karena dahsyatnya penyesalan, \"Alangkah baiknya sekiranya aku dahulu hanyalah tanah, sehingga aku tidak dibangkitkan dan tidak dihisab.\""
    ]
};

const naziatData = {
    arabic: [
        "وَالنّٰزِعٰتِ غَرْقًاۙ",
        "وَّالنّٰشِطٰتِ نَشْطًاۙ",
        "وَّالسّٰبِحٰتِ سَبْحًاۙ",
        "فَالسّٰبِقٰتِ سَبْقًاۙ",
        "فَالْمُدَبِّرٰتِ اَمْرًاۘ",
        "يَوْمَ تَرْجُفُ الرَّاجِفَةُۙ",
        "تَتْبَعُهَا الرَّادِفَةُۗ",
        "قُلُوْبٌ يَّوْمَىِٕذٍ وَّاجِفَةٌۙ",
        "اَبْصَارُهَا خَاشِعَةٌۘ",
        "يَقُوْلُوْنَ ءَاِنَّا لَمَرْدُوْدُوْنَ فِى الْحَافِرَةِۗ",
        "ءَاِذَا كُنَّا عِظَامًا نَّخِرَةًۗ",
        "قَالُوْا تِلْكَ اِذًا كَرَّةٌ خَاسِرَةٌۘ",
        "فَاِنَّمَا هِيَ زَجْرَةٌ وَّاحِدَةٌۙ",
        "فَاِذَا هُمْ بِالسَّاهِرَةِۗ",
        "هَلْ اَتٰىكَ حَدِيْثُ مُوْسٰىۘ",
        "اِذْ نَادٰىهُ رَبُّهٗ بِالْوَادِ الْمُقَدَّسِ طُوًىۚ",
        "اِذْهَبْ اِلٰى فِرْعَوْنَ اِنَّهٗ طَغٰىۙ",
        "فَقُلْ هَلْ لَّكَ اِلٰٓى اَنْ تَزَكّٰىۙ",
        "وَاَهْدِيَكَ اِلٰى رَبِّكَ فَتَخْشٰىۚ",
        "فَاَرٰىهُ الْاٰيَةَ الْكُبْرٰىۖ",
        "فَكَذَّبَ وَعَصٰىۖ",
        "ثُمَّ اَدْبَرَ يَسْعٰىۖ",
        "فَحَشَرَ فَنَادٰىۖ",
        "فَقَالَ اَنَا۠ رَبُّكُمُ الْاَعْلٰىۖ",
        "فَاَخَذَهُ اللّٰهُ نَكَالَ الْاٰخِرَةِ وَالْاُوْلٰىۗ",
        "اِنَّ فِيْ ذٰلِكَ لَعِبْرَةً لِّمَنْ يَّخْشٰىۗ",
        "ءَاَنْتُمْ اَشَدُّ خَلْقًا اَمِ السَّمَاۤءُ ۚ بَنٰهَاۗ",
        "رَفَعَ سَمْكَهَا فَسَوّٰهَاۙ",
        "وَاَغْطَشَ لَيْلَهَا وَاَخْرَجَ ضُحٰهَاۖ",
        "وَالْاَرْضَ بَعْدَ ذٰلِكَ دَحٰهَاۗ",
        "اَخْرَجَ مِنْهَا مَاۤءَهَا وَمَرْعٰهَاۖ",
        "وَالْجِبَالَ اَرْسٰهَاۙ",
        "مَتَاعًا لَّكُمْ وَلِاَنْعَامِكُمْۗ",
        "فَاِذَا جَاۤءَتِ الطَّامَّةُ الْكُبْرٰىۖ",
        "يَوْمَ يَتَذَكَّرُ الْاِنْسَانُ مَا سَعٰىۙ",
        "وَبُرِّزَتِ الْجَحِيْمُ لِمَنْ يَّرٰى",
        "فَاَمَّا مَنْ طَغٰىۙ",
        "وَاٰثَرَ الْحَيٰوةَ الدُّنْيَاۙ",
        "فَاِنَّ الْجَحِيْمَ هِيَ الْمَأْوٰىۗ",
        "وَاَمَّا مَنْ خَافَ مَقَامَ رَبِّهٖ وَنَهَى النَّفْسَ عَنِ الْهَوٰىۙ",
        "فَاِنَّ الْجَنَّةَ هِيَ الْمَأْوٰىۗ",
        "يَسْـَٔلُوْنَكَ عَنِ السَّاعَةِ اَيَّانَ مُرْسٰهَاۗ",
        "فِيْمَ اَنْتَ مِنْ ذِكْرٰهَاۗ",
        "اِلٰى رَبِّكَ مُنْتَهٰهَاۗ",
        "اِنَّمَآ اَنْتَ مُنْذِرُ مَنْ يَّخْشٰهَاۗ",
        "كَاَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوْٓا اِلَّا عَشِيَّةً اَوْ ضُحٰهَاࣖ"
    ],
    translation: [
        "Demi (malaikat-malaikat) yang mencabut (nyawa) dengan keras,",
        "demi (malaikat-malaikat) yang mencabut (nyawa) dengan lemah lembut,",
        "demi (malaikat-malaikat) yang turun dari langit dengan cepat,",
        "dan (malaikat-malaikat) yang mendahului dengan kencang,",
        "dan (malaikat-malaikat) yang mengatur urusan (dunia).",
        "Pada hari (ketika) tiupan pertama (sangkakala) mengguncang (alam semesta),",
        "(tiupan pertama) itu diiringi oleh tiupan kedua.",
        "Hati manusia pada waktu itu sangat takut,",
        "pandangannya tunduk.",
        "Mereka berkata, \"Apakah kita benar-benar akan dikembalikan kepada kehidupan yang semula?",
        "Apakah (akan dibangkitkan juga) apabila kita telah menjadi tulang belulang yang hancur?\"",
        "Mereka berkata, \"Kalau begitu, itu adalah pengembalian yang merugikan.\"",
        "Maka sesungguhnya (pengembalian itu) hanyalah dengan satu kali tiupan saja,",
        "maka seketika itu mereka hidup kembali di bumi (yang baru).",
        "Sudahkah sampai kepadamu (Muhammad) kisah Musa?",
        "Ketika Tuhannya menyerunya di lembah suci, yaitu Lembah Tuwa;",
        "\"Pergilah kepada Fir‘aun, sesungguhnya dia telah melampaui batas,",
        "maka katakanlah (kepada Fir‘aun), ‘Adakah keinginanmu untuk membersihkan diri (dari kesesatan),",
        "dan engkau akan kupimpin ke jalan Tuhanmu agar engkau takut kepada-Nya?\"\"",
        "Lalu (Musa) memperlihatkan kepadanya mukjizat yang besar.",
        "Tetapi dia (Fir‘aun) mendustakan dan mendurhakai.",
        "Kemudian dia berpaling seraya berusaha menantang (Musa).",
        "Kemudian dia mengumpulkan (orang-orangnya) lalu berseru memanggil,",
        "maka dia berkata, \"Akulah tuhanmu yang paling tinggi.\"",
        "Maka Allah menghukumnya dengan azab di akhirat dan siksaan di dunia.",
        "Sungguh, pada yang demikian itu terdapat pelajaran bagi orang yang takut (kepada Allah).",
        "Apakah penciptaan kamu yang lebih hebat ataukah langit yang telah dibangun-Nya?",
        "Dia telah meninggikan bangunannya lalu menyempurnakannya,",
        "dan Dia menjadikan malamnya (gelap gulita), dan menjadikan siangnya (terang benderang).",
        "Dan setelah itu bumi Dia hamparkan.",
        "Darinya Dia pancarkan mata air, dan (ditumbuhkan) tumbuh-tumbuhannya.",
        "Dan gunung-gunung Dia pancangkan dengan teguh,",
        "(semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu.",
        "Maka apabila malapetaka besar (hari Kiamat) telah datang,",
        "yaitu pada hari (ketika) manusia teringat akan apa yang telah dikerjakannya,",
        "dan neraka diperlihatkan dengan jelas kepada setiap orang yang melihat,",
        "maka adapun orang yang melampaui batas,",
        "dan lebih mengutamakan kehidupan dunia,",
        "maka sungguh, nerakalah tempat tinggalnya.",
        "Dan adapun orang-orang yang takut kepada kebesaran Tuhannya dan menahan diri dari (keinginan) hawa nafsunya,",
        "maka sungguh, surgalah tempat tinggal(nya).",
        "Mereka bertanya kepadamu (Muhammad) tentang hari Kiamat, \"Kapankah terjadinya?\"",
        "Untuk apa engkau perlu menyebutkannya (waktunya)?",
        "Kepada Tuhanmulah (dikembalikan) kesudahannya (ketentuan waktunya).",
        "Engkau (Muhammad) hanyalah pemberi peringatan bagi siapa yang takut kepadanya (hari Kiamat).",
        "Pada hari mereka melihat hari Kiamat itu, mereka merasa seakan-akan hanya (sebentar saja) tinggal (di dunia) pada waktu sore atau pagi hari."
    ],
    translation_en: [
        "By those [angels] who extract with violence,",
        "And [by] those who remove with ease,",
        "And [by] those who glide [as if] swimming,",
        "And those who race each other in a race,",
        "And those who arrange [each] matter.",
        "On the Day the blast [of the Horn] will convulse [creation],",
        "There will follow it the subsequent [one].",
        "Hearts, that Day, will tremble,",
        "Their eyes humbled.",
        "They are [presently] saying, \"Will we indeed be returned to [our] former state [of life]?",
        "Even if we should be decayed bones?\"",
        "They say, \"That, then, would be a losing return.\"",
        "Indeed, it will be but one shout,",
        "And suddenly they will be [alert] upon the earth's surface.",
        "Has there reached you the story of Moses?",
        "When his Lord called to him in the sacred valley of Tuwa,",
        "\"Go to Pharaoh. Indeed, he has transgressed.",
        "And say to him, 'Would you [be willing to] purify yourself,",
        "And let me guide you to your Lord so you would fear [Him]?'\"",
        "And he showed him the greatest sign,",
        "But Pharaoh denied and disobeyed.",
        "Then he turned his back, striving.",
        "And gathered [his people] and made a proclamation,",
        "Saying, \"I am your most exalted lord.\"",
        "So Allah seized him in exemplary punishment for the last and the first [transgression].",
        "Indeed in that is a warning for whoever would fear [Allah].",
        "Are you a more difficult creation or is the heaven?",
        "He constructed it.",
        "He raised its ceiling and proportioned it.",
        "And He darkened its night and extracted its brightness.",
        "And after that He spread the earth.",
        "He extracted from it its water and its pasture.",
        "And the mountains He set firmly [on the earth] –",
        "As provision for you and your grazing livestock.",
        "But when the greatest calamity comes –",
        "The Day when man will remember that for which he strove,",
        "And Hellfire will be displayed for [all] to see –",
        "Then as for he who transgressed,",
        "And preferred the life of this world,",
        "Then indeed, Hellfire will be [his] refuge.",
        "But as for he who feared the position of his Lord and prevented the soul from [unlawful] inclination,",
        "Then indeed, Paradise will be [his] refuge.",
        "They ask you, [O Muhammad], about the Hour: when is its arrival?",
        "In what [position] are you that you should mention it?",
        "To your Lord is its finality.",
        "You are only a warner for those who fear it.",
        "The Day they see it, it will be as though they had not remained [in the world] except for an afternoon or a morning thereof."
    ],
    translation_my: [
        "Demi malaikat-malaikat yang mencabut nyawa orang-orang kafir dengan keras.",
        "Demi malaikat-malaikat yang mencabut nyawa orang-orang mukmin dengan lembut.",
        "Demi malaikat-malaikat yang turun dari langit dengan cepat melaksanakan perintah Allah.",
        "Demi malaikat-malaikat yang berlomba-lomba melaksanakan perintah Allah.",
        "Demi malaikat-malaikat yang mengatur urusan dunia sesuai perintah Allah.",
        "Pada hari ketika tiupan pertama mengguncang alam semesta.",
        "Diiringi dengan tiupan kedua.",
        "Hati manusia pada hari itu sangat takut dan gelisah.",
        "Pandangannya tunduk dan hina.",
        "Orang-orang kafir berkata di dunia dengan nada mengingkari, \"Apakah kita benar-benar akan dikembalikan kepada kehidupan yang semula setelah kita mati?\"",
        "\"Apakah bila kita telah menjadi tulang belulang yang hancur (kita akan dibangkitkan)?\"",
        "Mereka berkata, \"Kalau begitu, pengembalian itu adalah pengembalian yang merugikan.\"",
        "Maka sesungguhnya kebangkitan itu hanyalah dengan satu kali tiupan saja.",
        "Maka tiba-tiba mereka hidup kembali di permukaan bumi.",
        "Sudahkah sampai kepadamu (wahai Muhammad) kisah Musa?",
        "Ketika Tuhannya memanggilnya di lembah suci Tuwa.",
        "\"Pergilah kepada Fir'aun, sesungguhnya dia telah melampaui batas dalam kekafiran dan kezaliman.",
        "Maka katakanlah kepadanya dengan lemah lembut, 'Adakah keinginanmu untuk membersihkan diri dari kekafiran dan dosa-dosa?",
        "Dan aku akan membimbingmu ke jalan Tuhanmu agar engkau takut kepada-Nya?'\"",
        "Lalu Musa memperlihatkan kepadanya mukjizat yang besar (tongkat dan tangan).",
        "Tetapi Fir'aun mendustakan Musa dan mendurhakai perintah Allah.",
        "Kemudian dia berpaling dari kebenaran seraya berusaha menantang.",
        "Lalu dia mengumpulkan kaumnya dan berseru memanggil mereka.",
        "Maka dia berkata dengan sombong, \"Akulah tuhanmu yang paling tinggi.\"",
        "Maka Allah membinasakannya dan menjadikannya pelajaran bagi umat manusia di akhirat dan di dunia.",
        "Sesungguhnya pada yang demikian itu terdapat pelajaran bagi orang yang takut kepada Allah.",
        "Apakah penciptaan kalian (wahai manusia) yang lebih sulit ataukah langit yang telah dibangun-Nya?",
        "Dia telah meninggikan bangunannya lalu menyempurnakannya tanpa cacat.",
        "Dan Dia menjadikan malamnya gelap gulita dan menjadikan siangnya terang benderang.",
        "Dan bumi sesudah itu dihamparkan-Nya agar layak dihuni.",
        "Dia memancarkan daripadanya mata air, dan menumbuhkan tumbuh-tumbuhannya.",
        "Dan gunung-gunung dipancangkan-Nya dengan kokoh.",
        "Semua itu untuk kesenangan kalian dan hewan-hewan ternak kalian.",
        "Maka apabila malapetaka yang sangat besar (hari Kiamat) telah datang.",
        "Pada hari ketika manusia teringat akan apa yang telah dikerjakannya di dunia.",
        "Dan neraka diperlihatkan dengan jelas kepada setiap orang yang melihat.",
        "Adapun orang yang melampaui batas dalam kekafiran.",
        "Dan lebih mengutamakan kehidupan dunia daripada akhirat.",
        "Maka sesungguhnya nerakalah tempat tinggalnya.",
        "Dan adapun orang-orang yang takut kepada kebesaran Tuhannya dan menahan diri dari keinginan hawa nafsunya yang buruk.",
        "Maka sesungguhnya surgalah tempat tinggalnya.",
        "Mereka (orang-orang kafir) bertanya kepadamu (wahai Muhammad) tentang hari Kiamat, \"Kapankah terjadinya?\"",
        "Untuk apa engkau menyebutkan waktunya? Engkau tidak mengetahuinya.",
        "Hanya kepada Tuhanmulah kesudahan ilmu tentang waktu terjadinya kiamat.",
        "Engkau hanyalah pemberi peringatan bagi siapa yang takut kepadanya.",
        "Pada hari mereka melihat hari Kiamat itu, mereka merasa seakan-akan mereka tidak tinggal (di dunia) melainkan hanya sesaat saja pada waktu sore atau pagi hari.\""
    ]
};

function writeFiles(surahCode, data) {
    const surahDir = path.join(KONTEN_DIR, surahCode);

    if (!fs.existsSync(surahDir)) fs.mkdirSync(surahDir, { recursive: true });
    if (!fs.existsSync(path.join(surahDir, 'arabic'))) fs.mkdirSync(path.join(surahDir, 'arabic'), { recursive: true });
    if (!fs.existsSync(path.join(surahDir, 'tr_id'))) fs.mkdirSync(path.join(surahDir, 'tr_id'), { recursive: true });

    if (!fs.existsSync(path.join(surahDir, 'tr_en_jl'))) fs.mkdirSync(path.join(surahDir, 'tr_en_jl'), { recursive: true });
    if (!fs.existsSync(path.join(surahDir, 'tr_id_my'))) fs.mkdirSync(path.join(surahDir, 'tr_id_my'), { recursive: true });

    data.arabic.forEach((text, index) => {
        fs.writeFileSync(path.join(surahDir, 'arabic', `${surahCode}_${index + 1}.txt`), text);
    });

    data.translation.forEach((text, index) => {
        fs.writeFileSync(path.join(surahDir, 'tr_id', `${surahCode}_${index + 1}.txt`), text);
    });

    if (data.translation_en) {
        data.translation_en.forEach((text, index) => {
            fs.writeFileSync(path.join(surahDir, 'tr_en_jl', `${surahCode}_${index + 1}.txt`), text);
        });
    }

    if (data.translation_my) {
        data.translation_my.forEach((text, index) => {
            fs.writeFileSync(path.join(surahDir, 'tr_id_my', `${surahCode}_${index + 1}.txt`), text);
        });
    }

    console.log(`Populated ${surahCode} with ${data.arabic.length} verses.`);
}

writeFiles('naba', nabaData);
writeFiles('naziat', naziatData);
